version: '3.9'

services:
  backend:
    build:
      context: ./iot-locker
    container_name: iot_backend
    volumes:
      - ./iot-locker:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - iot_network

  frontend:
    build:
      context: ./frontend
    container_name: iot_frontend
    depends_on:
      - backend
    networks:
      - iot_network

  db:
    image: mysql:8.0
    container_name: iot_mysql
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - iot_network

volumes:
  db_data:

networks:
  iot_network:
    driver: bridge
